  name: Oblig3 - git og continuous integration


  on:
    push:
      branches: [main]

  jobs:
    build:

      runs-on: ubuntu-latest
      steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4

      - name: Sette opp JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Bygge maven
        run: mvn -B package --file pom.xml

